### ISSUE TITLE
Module does not install on windows

### ISSUE THREAD

**Issue by arnesom** [MARTIMM/perl6-gnome-gtk3#16]
Windows 10 with MSYS2.

See this link for details: https://stackoverflow.com/questions/65161840/raku-installation-of-gnomegtk3-on-windows/65438246#65438246

**Comment by MARTIMM** [comment]
Hi Arne, I find it difficult to get a solution for the problems you are facing. I only have a few packages tested succesfully on Appveyor a short time ago and that was only by having luck instead of wisdom.

I followed the discussion on stackoverflow but cannot answer anything there because of lack of points or whatever.

If you can, talk a bit more with Håkon Hægland. I understood in the latest conversations with him that he got it running on his machine.

In the mean time, I try to get the documentation a bit better.

**Comment by MARTIMM** [comment]
The Boxed.t script is a very simple test script and I am afraid this iscaused by a known Raku problem which I filed some while ago (issue #3722). Shuffling use statements up or down can change the behavior.

**Comment by arnesom** [comment]
All I tried to do was get my "Game::Amazing" module  (and bundled programs) to work on Windows. For somebody else, as I don't even have a pc with windows...

I cannot give any input on the "use" issue, but do think that the 19 "use Gnome::*" statements required in my "amazing-gtk" program is somewhat excessive.

**Comment by MARTIMM** [comment]
I've cloned your project and run `amazing-gtk` on my Fedora system without problems. Funny layout to use these characters to create a labyrinth, I like it.

The use statements are about separate classes around semi 'classes' in the C implementation of GTK+. It is a very large set of different widgets from `gtk` and helper modules from `gdk`, `glib`, `gio`, `cairo` etc. and should not be placed in one module.

It is a pity that the Gnome::* code is getting very large and because of that, the programs are starting up slow. I am working at it to get it a bit faster but that will take a while. And, the Raku compiler is still getting better, so perhaps in the near future we won't have to wait too long to see our gems in action.

**Comment by MARTIMM** [comment]
I have managed to get **Gnome::Gtk3** working on `Appveyor` using msys2 and installing Raku from git.
