### ISSUE TITLE
Can't create signal for DrawingArea

### ISSUE THREAD

**Issue by grenzionky** [MARTIMM/perl6-gnome-gtk3#18]
```
use Gnome::Gtk3::DrawingArea;
use Gnome::Gtk3::Main;
use Gnome::Gtk3::Window;
use Gnome::Gtk3::Fixed;

my Gnome::Gtk3::Main $m .= new;
my Gnome::Gtk3::Window $top-window .= new;
my Gnome::Gtk3::Fixed $fixed .= new;
my Gnome::Gtk3::DrawingArea $draw .= new;


class AppSignalHandlers {
	method exit() { $m.main-quit; }

	method draw() {
             say 'drew';
        }
}
my AppSignalHandlers $ash .= new;

$top-window.register-signal($ash, 'exit', 'destroy');
$draw.register-signal($ash, 'draw', 'draw');

$top-window.add($fixed);
$fixed.put($draw, 0,0);

$top-window.show-all;
$m.main;
```

This code (which i put in a file test.raku) crashes right away and quits with the following error:

```
Unhandled exception: Too few positionals passed; expected 3 arguments but got 2
   at home#sources/F6AA9E9400E2588222D42E8EBDAC014B28828C6A (Gnome::GObject::Object):650  (/home/user/.raku/precomp/CC223920E11FB7316B7A8382326F9624B92C2B9E/F6/F6AA9E9400E2588222D42E8EBDAC014B28828C6A:w1)
 from core#sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall):595  (/usr/share/perl6/core/precomp/CC223920E11FB7316B7A8382326F9624B92C2B9E/94/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B:)
 from home#sources/B402161F1A1700B2A55800B42CCB62970438CA23 (Gnome::Gtk3::Main):825  (/home/user/.raku/precomp/CC223920E11FB7316B7A8382326F9624B92C2B9E/B4/B402161F1A1700B2A55800B42CCB62970438CA23:main)
 from test.raku:26  (<ephemeral file>:<unit>)
 from test.raku:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1946  (/usr/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2151  (/usr/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:2081  (/usr/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:109  (/usr/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2036  (/usr/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:127  (/usr/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (/usr/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/usr/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/usr/share/perl6/runtime/perl6.moarvm:<entry>)
```

Any help on how to do this properly would be really appreciated

**Comment by MARTIMM** [comment]
I did not yet document the draw signal on the Widget because of a false thought that I did not yet have the CairoContext in the **Gnome::Cairo** package. The cairo context, however, is the `cairo_t` from that package. Anyways, the main problem however why the call fails is because you must describe the signal handler signature precisely. The gnome documents describe it like
```
gboolean
user_function (GtkWidget    *widget,
               CairoContext *cr,
               gpointer      user_data
)
```
The widget and user_data normally are provided as `:$_widget` and any `:$user-data` as named arguments. Those are optional and you don't need to describe them if you don't need them. However, the `cairo_t` parameter is obligatory; its position and its type. 

So your draw handler must be something like below to get rid of the errors
```
use Gnome::Cairo::Types;
…
  method draw( cairo_t $cr ) {
    say 'drew';
  }
…
To get something working you must do much more. Please look
```
You can find a few examples in the `xt` directory of the **Gnome::Cairo** package. Especially `xt/c5.raku`.

**Comment by grenzionky** [comment]
it worked! thanks!

**Comment by MARTIMM** [comment]
https://github.com/MARTIMM/gnome-cairo/blob/master/xt/c5.pl6

**Comment by grenzionky** [comment]
c5.pl doesnt run for me, it gives me an error 

```
width & height: 333 x 253
X valid: True
X surface state: CAIRO_STATUS_SUCCESS
X surface type: CAIRO_SURFACE_TYPE_XLIB
X surface content: CAIRO_CONTENT_COLOR_ALPHA
X surface device: cairo_device_t.new
width & height: 266 x 566
X valid: True
X surface state: CAIRO_STATUS_SUCCESS
X surface type: CAIRO_SURFACE_TYPE_XLIB
X surface content: CAIRO_CONTENT_COLOR_ALPHA
X surface device: cairo_device_t.new
width & height: 198 x 592
Y valid: True
Y surface state: CAIRO_STATUS_SUCCESS
Y surface type: CAIRO_SURFACE_TYPE_XLIB
Y surface content: CAIRO_CONTENT_COLOR_ALPHA
Y surface device: cairo_device_t.new
Type check failed in binding to parameter '$cr'; expected cairo_t but got Gnome::Cairo (Gnome::Cairo.new(is-...)
  in method draw at /home/user/.raku/sources/3094BC8DA65E28532F5887D988415015DCC37340 (Gnome::Gtk3::Widget) line 1291
  in method redraw at c5.pl6 line 226
  in sub w1 at /home/user/.raku/sources/F6AA9E9400E2588222D42E8EBDAC014B28828C6A (Gnome::GObject::Object) line 658
  in sub gtk_main at /usr/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 595
  in method FALLBACK at /home/user/.raku/sources/B402161F1A1700B2A55800B42CCB62970438CA23 (Gnome::Gtk3::Main) line 131

Cannot unbox a type object (Nil) to int.
  in sub gtk_main at /usr/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 595
  in method FALLBACK at /home/user/.raku/sources/B402161F1A1700B2A55800B42CCB62970438CA23 (Gnome::Gtk3::Main) line 131
  in block <unit> at c5.pl6 line 333

Died
  in method FALLBACK at /home/user/.raku/sources/B402161F1A1700B2A55800B42CCB62970438CA23 (Gnome::Gtk3::Main) line 118
  in block <unit> at c5.pl6 line 333

```

**Comment by MARTIMM** [comment]
I found a bug in method draw() in the Widget module expecting this cairo_t. This is already corrected but not yet published. Problem is that I also had to make changes in other packages as well and they must be published all at the same time because of dependencies. I'll try to get it done soon but don't want to make more mistakes either.

**Comment by grenzionky** [comment]
Since I have your attention, is it currently possible to attach an EntryCompletion onto a SearchEntry using your amazing module? 

I can't find the EntryCompletion class, so I thought that maybe through a N-GObject or a GObject it might be possible but I haven't been able to get it to work.

**Comment by MARTIMM** [comment]
Hi,
I haven't yet implemented the EntryCompletion class. To get it fully functioning, I also must implement a role GtkCellLayout to make it more useful. For me, it is not yet clear which module I need to implement first and in which package. Because I was also busy writing tutorials for the Application classes and everything needed to build a complete application I was more thinking in the line of those classes involving actions and menus. Anyways, it is open for debate I assume.

There is also much rewriting going on at the moment which will break code, unfortunately. Mostly the changes are in the line of returned native objects. But now that I am adding methods for each native subroutine, these methods know at that point what to return and can therefore create a Raku object instead. Also, I can then receive and return Bool values instead of the C-integers 0 or 1 for false and true. Other types can be converted as well.

But, first things first, I need to finish the above-mentioned work!

**Comment by MARTIMM** [comment]
Pushed new versions;
Gnome::Glib 0.20.0
Gnome::Gio 0.18.0.1
Gnome::Gdk3 0.17.3
Gnome::Gtk3 0.37.0

**Comment by MARTIMM** [comment]
Gnome::Gtk3 0.38.0 contains **Gnome::Gtk3::EntryCompletion** now. Knock yourself out ;-)
