### ISSUE TITLE
Container.get-children causes application to freeze

### ISSUE THREAD

**Issue by grenzionky** [MARTIMM/perl6-gnome-gtk3#20]
whenever I call get-children on a container node (grid, list, etc) my entire program freezes...

heres a small sample project (from the demo projects) with a get-children attached.
Once the window opens click on the top button and the program will freeze.

```
use Gnome::Gtk3::Main;
use Gnome::Gtk3::Window;
use Gnome::Gtk3::Button;
use Gnome::Gtk3::Grid;

#instantiate main module for UI control 
my Gnome::Gtk3::Main $m .= new;
#create grid
my Gnome::Gtk3::Grid $grid .= new;

# A callback handler class to respond to signals
class AppSignalHandlers {
	method exit-program() { $m.gtk-main-quit; }

	method first-button-click ( :widget($b1), :other-button($b2) ) {
		$b1.set-sensitive(False);
		$b2.set-sensitive(True);
		say $grid.get-children;
	}
	method second-button-clicked() { $m.gtk-main-quit; }
}

#create a top level window and set a title
my Gnome::Gtk3::Window $top-window .= new;
$top-window.set-border-width(20);
$top-window.set-title("Example");

$top-window.add($grid);
# create button
#my Gnome::Gtk3::Button $button1 .= new(:label('Exit program'));
#my Gnome::Gtk3::Button $button2 .= new(:label('also Exit program'));
my Gnome::Gtk3::Button $button1 .= new(:label('hello world'));
my Gnome::Gtk3::Button $button2 .= new(:label('goodbye'));
#disable second button
$button2.set-sensitive(False);

# add buttons to the grid
$grid.attach($button1, 0,0,2,1);
$grid.attach($button2, 0, 1, 1, 1);


# set up signal event handler
my AppSignalHandlers $ash .= new;
$top-window.register-signal($ash, 'exit-program', 'destroy');
$button1.register-signal($ash, 'first-button-click', 'clicked', :other-button($button2));
$button2.register-signal($ash, 'second-button-clicked', 'clicked');

# show everything and activate
$top-window.gtk-widget-show-all;

$m.gtk-main;
```

**Comment by MARTIMM** [comment]
Hi,
I am not really sure why `say()` hangs up like that. The object returned is an `N-GObject` which is not known there so maybe it's that. Changing a few lines there into
```
…
use Gnome::Glib::List;
…

method first-button-click ( :_widget($b1), :other-button($b2), :$container ) {
  $b1.set-sensitive(False);
  $b2.set-sensitive(True);

  my Gnome::Glib::List $l .= new(
    :native-object($container.get-children)
  );
  note 'nbr widgets: ', $l.length;
}
```
There are a few small things I'd like to mention;
* Use `:_widget` instead of `:widget`. (I must check the examples …). This is done to give users a free hand in providing their own named arguments. Then all names starting with '_' are reserved by the program. Another one is `:_handler-id`.
* I've introduced :$container to import the $grid. It does work however when you refer to it directly and in tests like this, there should be no harm. It is safer however when you provide the grid in the method arguments list. The call to the register-signal; 
```
$button1.register-signal(
  $ash, 'first-button-click', 'clicked', :other-button($button2),
  :container($grid)
);
```
* In a later update of the **Gnome::Gtk3::Container** module, where the method `.get-children()` comes from, the routine will return **Gnome::Glib::List** directly and this code will break. Problem is that I can not make multi-methods based on return types.

**Comment by grenzionky** [comment]
In “Example 1, a while loop to visit all widgets in a grid” in the https://martimm.github.io/gnome-gtk3/content-docs/reference/Glib/List.html page it says:

```
# Get the objects from the grid in a list
my Gnome::Glib::List $list .= new(
  :native-object($grid.get-children)
);

while $list.is-valid {
  # Do something with data at $list.data
  my N-GObject $no = $list.data;
  my Gnome::Gtk3::Widget $w .= new(:native-object($no));

  # Names can be set but are like 'GtkLabel', GtkButton', etc. by default
  given $w.get-name {
    when 'GtkLabel' {
      my Gnome::Gtk3::Label $hl .= new(:native-object($no));
      …
    }
    …
  }

  $list .= next;
}

$list.clear-object;
```

But none of it works… I get an error `Cannot look up attributes in a Gnome::Glib::List type object` when I try to do `$list.is-valid` and when I try to do `$list.clear-object` etc. Please advise on what I should do

**Comment by MARTIMM** [comment]
Do you have some code for me where you have used this example? You must be aware that the above code can only work when the grid is defined and have some widgets attached to it.
