### ISSUE TITLE
How to go through each page in a GtkNotebook

### ISSUE THREAD

**Issue by grenzionky** [MARTIMM/perl6-gnome-gtk3#23]
```
my Gnome::Gtk3::Notebook $nb .= new;
... add pages ...
for ^$nb.get-n-pages -> $i {
	# replace grid with whatever you have
	my Gnome::Gtk3::Grid $contents .= new(:native-object($nb.get-nth-page($i)));
}
```

I can do this ↑ and it will technically work, but the problem is that it creates a new object - which doesn't know about any of the properties that are set (thus defeating the purpose of what I need).

So I guess what I'm really asking is: is there a way to get a gtk object without having to do `.new`. (maybe you can a -rk method to get-nth-page or something like that)

**Comment by MARTIMM** [comment]
Well, I can make a `.get-nth-page-rk()` for you but it will do exactly the same as you are doing now. Besides, all information and properties, etc. are held in that returned native object. It is only imported here. For the rest, most classes are only a kind of wrapper around that native object with definitions of subs to get to the native ones.

Could you also elaborate a bit more on the properties not being the same as when initialized?

In the meantime, I can improve the **Notebook** module for you.

**Comment by grenzionky** [comment]
```
use Gnome::Gtk3::Main;
use Gnome::Gtk3::Window;
use Gnome::Gtk3::Label;
use Gnome::Gtk3::Notebook;

my Gnome::Gtk3::Main $m .= new;
my Gnome::Gtk3::Window $w .= new;
my Gnome::Gtk3::Notebook $nb .= new;

class ExtendedLabel is Gnome::Gtk3::Label {
	has Str $.custom-data;
	submethod new (|c) {
		self.bless( :GtkLabel, |c );
	}
}

class Handlers {
	method on-close {
		$m.quit;
	}
}

my ExtendedLabel $label .= new(:custom-data('some data contents'), :text('words'));
my Handlers $handler .= new;

$w.add($nb);
$nb.append-page($label, Gnome::Gtk3::Label.new(:text('title')));

$w.show-all;
$w.register-signal($handler, 'on-close', 'destroy');


# ... later in the program ...
# should return 'some data contents'
say ExtendedLabel.new(:native-object($nb.get-nth-page($nb.get-n-pages-1))).custom-data;

$m.main;
```

I made a full example of what I mean so that you can see what I'm taking about

**Comment by MARTIMM** [comment]
I understand what is happening here. I already was afraid of that. You see, the class **ExtendedLabel** 'is a' **Label** that holds the native object for a `GtkLabel`. Only that native object is stored on the **Notebook** as a page and therefore only that can be returned by the call to `.get-nth-page()` and not the attributes held by the **ExtendedLabel** class.

I have to think hard to find a solution for that if I can find one. For the moment you could do the following;
```
# ... later in the program ...
# should return 'some data contents'
$label.set-native-object-no-reffing($nb.get-nth-page($nb.get-n-pages - 1));
say $label.custom-data;
```
This means that you have to keep the **ExtendedLabel** object around.

I haven't yet documented the routines `.set-native-object-no-reffing()` and `.set-native-object()` because I still do not have a clear picture of the referencing system in Gtk. So this could change when I have to correct things to prevent memory leaks.

**Comment by grenzionky** [comment]
If the "later in the program" bit is in another file/class, I wouldn't have access to `$label` there, so how would I be able to use `.set-native-object-no-reffing()` or get `.custom-data`?

**Comment by MARTIMM** [comment]
It won't be useful because the `$label` object has the info, not the native object! The method is just importing the native object back into that object. Now I think about it, the example I gave was not a very good one because with that call I only have overwritten the native object which was already there, so that is not a solution.

But, what you could do is make some registration of objects and set a key to each object you would like to preserve. This registration class can be made using a Singleton design pattern.
```
class ObjectRegistration {
  my ObjectRegistration $instance;
  has Hash $registrations;

  method new ( ) { !!! } # prevent using new()

  submethod BUILD ( :$some-option ) {
    $registrations = %();
    # rest of inits
  }

  method instance ( |c --> ObjectRegistration ) {
      $instance //= self.bless(|c);
      $instance
  }

  method set ( Str $key, $obj ) {
     $registrations{$key} = $obj;     # overwriting possible!
  }

  method get ( Str $key --> Any ) {
    $registrations{$key}                  # wrong ones possible
  }

  method clear ( Str $key ) {
    $registration{$key}:delete;
  }
}

```
Usage can then be;
```
my ExtendedLabel $label .= new(:custom-data('some data contents'), :text('words'));
$label.set-name('myNotebookPage');
ObjectRegistration.instance.set( 'myNotebookPage', $label);
…
# ... later in the program ...
# should return 'some data contents'
my Gnome::Gtk3::Widget $wdgt .= new(
  :native-object($nb.get-nth-page($some-page))
);
my ExtendedLabel $label-somewhere-else = ObjectRegistration.instance.get(
  $wdgt.get-name
);
$wdgt.clear-object;
say $label-somewhere-else.custom-data;
```
The key of an object in the registration is also stored in the native object as its name. This is also a nice way to scan over e.g. grid components and recognize what the objects should be by investigating its name of the native object.

For the rest it looks a bit awkward; first making a **Widget** object and then get the **ExtendedLabel** and then destroy the widget again to set the reference counting right.
Maybe with a call like `.get-nth-page-rk(),` it becomes a tiny bit simpler. 

All this is not needed when the child classes only change the native objects to their liking and do not have info of their own in attributes.
