### ISSUE TITLE
Failed during Testing: Gnome::Glib:ver<0.14.4>

### ISSUE THREAD

**Issue by hkdtam** [MARTIMM/perl6-gnome-gtk3#5]
Hi,

Thanks for your nice module.

I got the following errors during installation, not sure if it is because of my little aged environment .

```===> Testing: Gnome::N:ver<0.13.8>
===> Testing [OK] for Gnome::N:ver<0.13.8>
===> Testing: Gnome::Glib:ver<0.14.4>
[Gnome::Glib]     # .clear-error()
[Gnome::Glib]     # Failed test 'domain is 3; 3rd domain registration in this test'
[Gnome::Glib]     # at t/Error.t line 119
[Gnome::Glib]     # expected: '3'
[Gnome::Glib]     #      got: '4'
[Gnome::Glib]     # Failed test 'Failed to open file 'unknown-file.txt': No such file or directory'
[Gnome::Glib]     # at t/Error.t line 126
[Gnome::Glib]     # expected: 'Failed to open file \u201cunknown-file.txt\u201d: No such file or directory'
[Gnome::Glib]     #      got: 'Failed to open file 'unknown-file.txt': No such file or directory'
[Gnome::Glib]     # You failed 2 tests of 8
[Gnome::Glib] # Failed test 'A real error'
[Gnome::Glib] # at t/Error.t line 101
[Gnome::Glib] # You failed 1 test of 3
===> Testing [FAIL]: Gnome::Glib:ver<0.14.4>
Aborting due to test failure: Gnome::Glib:ver<0.14.4> (use --force-test to override)
```
```
name -a
Linux myhost 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
dpkg -l | fgrep gtk-3-dev
ii  libgtk-3-dev                                          3.10.8-0ubuntu1.6                                    amd64        development files for the GTK+ library
```

Thanks in advance for your help.

**Comment by MARTIMM** [comment]
Hi,
There are two things here going wrong but luckily it is not a failing module.

The domain in the above error is a count in registrations of the error messages in the glib system to keep things unique. So after using a few classes which define some errors it should have been 3. What I can think of is that I am totally wrong here or that there is some work done in the background where other items get registered.
I will skip this test.

The other error is a text message where somehow some unprintable characters are inserted in the to be expected message in the Perl6 test script, double quote gets translated in \u201c and \u201d which I find strange. For the moment this test is changed a bit to circumvent the double-quotes. This is perhaps a UTF-8 issue, I don't know.

Btw, the packages need the newest Rakudo versions because of the use of some newly implemented tricks in the native call system (about summer 2019).

I will create a new version of this module shortly and hopefully, it will finish without new problems.

**Comment by MARTIMM** [comment]
oops, wrong button. first wait and then close.... (yes sir)

**Comment by hkdtam** [comment]
Hi Marcel,

Thanks for your very prompt feedback.

Sorry I guess I reported too immaturely.  I just downloaded the module and tried a manual install again.  Over the error log there are several notices about requiring gtk+v3.20 while mine is v3.10.  For the record I put that log on [pastebin](https://pastebin.com/9DUjKzze) for your perusal as well.

I will patch up my environment first and then try again.

Thanks again for your time and effort.

Regards,
David.

**Comment by MARTIMM** [comment]
@hkdtam 
Hi
I was wondering how you are doing. I am very much interested in user experience.

Regards,

**Comment by hkdtam** [comment]
Hi Marcel,

Thanks for the hospitality. 

>> I was wondering how you are doing.

My box is an Ubuntu 14.04 machine which is already EOL on package support (distro default for libgtk+3-dev is [v3.10.8](https://launchpad.net/ubuntu/trusty/+package/libgtk-3-dev)).  To go further I have to either compile it myself or use a newer Ubuntu.  In the long run I prefer the latter so I will build a virtual machine with Ubuntu 18.04 which provides [v3.22.30](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libgtk&searchon=names)

I will let you know once it is ready, thanks again.

Regards,
David.
